server:
  port: 3333

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: config-center3333

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/fys22/sprincloud-config.git
          search-paths:
            - springcloud-config
          username: 1186421205@qq.com
          password: fys440184
      label: master

#rabbitmq相关配置，
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#暴露bus刷新配置的端点
management:
  endpoints:  #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'
