server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态生成路由的功能，用微服务名进行路由
      routes:
        - id: payment_route1
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE  #负载均衡
          predicates:
            - Path=/payment/selectOne/**

        - id: payment_route2
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE  #负载均衡
          predicates:
            - Path=/payment/lb

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: gateway9527
    prefer-ip-address: true

