server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka/
  instance:
    instance-id: orderFeign80
    prefer-ip-address: true

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
logging:
  level:
    com.fys.service.PaymentFeignService: debug
