server:
  port: 8001

spring:
  application:
    name: cloud-provider-payment

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    ip-address: 127.0.0.1
    instance-id: payment8001
    prefer-ip-address: true