server:
  port: 80

spring:
  application:
    name: cloud-comsumer-order
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: order80
    prefer-ip-address: true


feign:
  hystrix:
    enabled: true  #在feign中开启hystrix